import { environment } from '../../environments/environment'


export const apiUrls = {
    baseUrl: `${environment.baseUrl}`,
    singup: '/educator/register',
    login:'/admin/login',
    logout:'/logout',
    sendForgetPasswordLink:'/admin/sendForgetPasswordLink',
    forgetPassword:'/admin/forgetPassword',
    educatorHistoricalSpend:'/educator/historicalSpend',
    educatorHistoricalSpendDetail:'/educator/historicalSpendDetail',
    educatorCurrentPlan:'/educator/currentMembership',
    calculateCreditPrize :'/educator/calculateCreditPrice',
    changeMembership: '/educator/changeMembership',
    createCustomer : '/membership/createCustomer',
    membershipToken : '/membership/token',
    membershipCreateCard :'/membership/createCard',
    membershipListCard : '/membership/listCards',
    membershipDeleteCard : '/membership/deleteCard',
    membershipMakeCharge : '/membership/makeCharge',
    membershipMakeChargeThroughToken :'/membership/makeChargeThroughToken',
    library:'/message/data',
    libraryList:'/message/data',
    messageList:'/message/list',
    tags:'/tag/all',
    addStudent:'/admin/studentDirectory',
    studentList:'/admin/studentDirectory',
    formList : '/educator/formsList',
    classlist:'/admin/classList',
    yearList:'/admin/yearList',
    filterYear:'/admin/studentList',
    studentDetail:'/admin/getStudentDetail',
    messageExchange:'/admin/MessageExchange',
    careerGoal:'/admin/careerGoalsList',
    achivements:'/admin/achivementsInterestsList',
    addClass:'/admin/addClass',
    filterClass:'/admin/studentList',
    filterStatus:'/admin/studentList',
    deleteStudent:'/admin/studentDelete',
    editClass:'/admin/editClass',
    editYear:'/admin/editStudentYear',
    editStudentClass:'/admin/editStudentClass',
    deleteClass:'/admin/deleteClass',
    uploadStudent:'/admin/bulkUpload',
    educatotDashboard:'/educator/dashBoardData',
    listLibrary:'/Library',
    studentClassDetail:'/admin/classDetail',
    sectorDummyList:'/sector',
    collegeDataDummyList:'/collegeData',
    employersDataDummyList:'/employersData',
    typeOfJobDummyList:'/typeOfJob',
    feildOfStudyDummyList:'/feildOfStudy',
    upvotes:'/upvotes',
    views:'/views',
    markfavorites :'/markfavorites',
    toDoList:'/todoList',
    memberShipeKey:'/membership/getkey',
    membershipCreateSession:'/membership/createSession',
    membershipTransationStatus:'/membership/checkTransaction',
    upgradeMembership:'/educator/upgradeMembership',
    membershipListData :'/educator/membershipList',
    updateCard : '/membership/updateCards',
    purchaseMembership : '/educator/purchaseMembership',
    notification : '/notification',
    educatorNotification : '/educator/notificationEducator',
    educatorBalanceDue : '/educator/balanceDue',
    educatorStudentDropdown : '/educator/studentDropdown',
    advisorInfo : '/advisor/advisorInfo',
   


    inviteStudent:'/admin/sendInvite',
    updateStudentPassword:'/admin/setPassword',
    updateEducatorPasswword:'/educator/setPassword',
    downloadTemplate:'/studentRecord.csv',
    studentCreditRequest:'/admin/creditRequestListing',
    approveCreditRequest:'/admin/approveCreditRequest',
    declineCreditRequest:'/admin/declinedCredit',
    checkToken:'/admin/checkForToken',
    educatorSchoolName :'/educator/schoolName',
    genrateInvoice : '/educator/InvoiceGenerate',
    // creditListCount :'/admin/creditListCount',
    creditInvoice :'/educator/InvoiceGenerateForCredit',
    membershipInvoice :'/educator/InvoiceGenerate',

    // educator billing & credits

    membershipPrize:'/educator/membershipPrize',
    membershipList:'/membership/membershipData',
    educatorBilling:'/educator/billings',
    creditCount:'/admin/creditCount',
    creditListCount:'/admin/creditListCount',
    educatorBillingList :'/educator/billingsList',
    educatorMonthyExpanse : '/educator/monthlyExpanse',
    educatorAmountToPay : '/educator/amountToPay',
    amountIsPaid : '/educator/isPaid',
    educatorMembershipPrice :'/educator/membershipPrice',
    educatorUpdateMembership :'/educator/upgradeMembership',
    educatorMembershipInfo :'/educator/membershipInfo',
    makeNotificationRead :'/makeNotificationRead',
    makeEducatorNotificationRead : '/educator/makeNotificationRead',
    checkInboxMessage :'/checkInboxMessage',
    checkForMessageType :'/educator/checkForMessageType',
    // checkBalance : '/student/checkBalance',
    insufficientModal: '/admin/checkBalance',
    thumbnailImage: '/thumbnailImage',
    membershipCardDetails: '/membership/cardDetail',


    //student my-message
    studentDashboard:'/studentDashboard',
    outbox:'/outboxMessage',
    draftbox:'/draftMessage',
    inbox:'/inboxListing',
    archive:'/archiveMessage',
    messageDetails:'/messageDetail',
    messageDetailLive:'/messageDetailLive',
    sendNow:'/sendNow',
    deleteMessage:'/deleteMessage',
    messageRead:'/makeMessageRead',
    newExchange:'/message',
    updateMessage:'/updateMessage',
    saveAsDraft:'/saveAsDraft',
    sector:'/getAllTags',
    adviceList:'/adviceList',
    collegeList:'/collegeList',
    jobList:'/jobList',
    employersList:'/employersList',
    messageThreadDetails:'/messageThreadDetail',
    sendReply:'/sendReply',
    newMessageExchnage:'/draftMessageNewMessageExchange',
    saveAsDraftLive:'/saveAsDraftLive',
    deleteNewMessage:'/deleteMessageNew',
    markMessageComplete:'/markMessageComplete',
    ratingsAndReviews:'/ratingsAndReviews',
    viewStatics:'/viewStatics',
    checkBalance:'/checkBalance',
    archiveMessageFilter:'/archiveMessageFilter',
    deleteMessageLive:'/deleteMessageLive',
    updateMessageLive:'/updateMessageLive',
    sendReplyLiveDraft:'/sendReplyLiveDraft',
    SendPropairSupport:'/SendPropairSupport',
    propairSupportList:'/propairSupportList',
    messageThreadDetailPropair:'/messageThreadDetailPropair',
    SendReplyPropairSupport:'/SendReplyPropairSupport',
    fileUpload:'/fileUpload',
    deleteMessagePropairSupport:'/deleteMessagePropairSupport',
    propairSupportListFilter:'/propairSupportListFilter',
    sendUpdatedOutBox:'/sendUpdatedOutBox',
    inboxListingFilter:'/inboxListingFilter',
    sendCreditRequest:'/admin/sendCreditRequest',
    calculatePrize:'/calculatePrice',
    creditGenral:'/admin/creditGeneral',
    countryData:'/educator/countryList',
    cityData:'/educator/cityList',
    removeImage :'/removeImages',

    //Advisor Student-requests
    messageRequest : '/advisor/messageRequest',
    acceptRequest : '/advisor/acceptMessage',

    updateAdvisorProfile: '/advisor/updateProfile',
    updateAdvisorPassword:'/educator/changePassword',
    inviteLink:'/advisor/sendReferral',
    advisorViews:'/advisor/increaseViews',
    advisorViewsList:'/advisor/viewsList',
    advisorRegisterThroughReferral:'/advisor/advisorRegisterThroughreferral',
    segemntApiForCollege :'/segemntApiForCollege'

    

 

}